# fly.toml app configuration file generated for coffee-order on 2023-09-15T13:39:18-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "coffee-order"
primary_region = "ord"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
